name: Python package

on:
  push:
  schedule:
  - cron:  '0 2 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pygithub

      - name: Manage Deploy PRs
        run: |
          from github import Github as GH

          g = GH(${{ secrets.MY_PAT }})
          r = g.get_repo('ajbarga/word-game')
          for pr in r.get_pulls():

            print(f'{pr.name}: {pr.base}')
            if pr.base == 'gh-pages' and 'deploy' in pr.head:
              pr.edit(status="closed")
              print(r.get_branch(f'{pr.head}').name)
        shell: python
