name: Deploy
on:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup NPM
        run: |
          npm i
          set -e

      - name: Build
        run: npm run build

      - name: Commit build
        run: |
          cd dist
          git init
          git checkout -B deploy
          git add .
          git commit -m 'Deploy Build'
          git push -f -u origin deploy-branch
