name: Build Site to Deploy
on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build Site
    if: ${{ contains(github.event.head_commit.message, '#B') }}
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      REPO: ${{ github.repository }}
      BASE: gh-pages
      BRANCH: deploy/run${{ github.run_id }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
          
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Configure Git
        run: |
          git config --global user.email actions@no-reply.github.com
          git config --global user.name github-actions

      - name: Build Site
        run: |
          npm ci
          npm run build

      - name: Create and Push Build to Branch
        run: |
          mkdir deploy
          cd deploy
          git clone https://${{ secrets.MY_PAT }}@github.com/${{ env.REPO }}.git
          cd word-game
          git checkout --force ${{ env.BASE }}
          git checkout -b ${{ env.BRANCH }}
          rm -rf ./assets
          rm -rf index.html
          mv -f ../../dist/* .
          git add -f .
          git commit -m "Deploy Build to GH Pages"
          git push -f -u origin ${{ env.BRANCH }}
          

      - name: Create PR for Build
        run: |
          gh pr create \
            --repo ${{ env.REPO }} \
            --reviewer ajbarga \
            --base ${{ env.BASE }} \
            --head ${{ env.BRANCH }} \
            --title "${{ github.event.head_commit.message }}" \
            --body "Created automatically by merge to main for @${{ github.actor }}."
            
