on:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      REPO: ajbarga/word-game
      HEAD: gh-pages
      BRANCH: deploy/${{ github.run_id }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
          
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Configure Git
        run: |
          git config --global user.email actions@no-reply.github.com
          git config --global user.name ${{ github.actor }}

      - name: Build Site
        run: |
          npm i
          npm run build

      - name: Initialize Repo for GH Pages PR
        run: |
          git clone https://${{ secrets.MY_PAT }}@github.com/${{ env.REPO }}.git
          cd word-game
          git checkout --force ${{ env.BASE }}
          git checkout -b ${{ env.BRANCH }}
          mv -f ../dist/*.* .
          git add -f .
          git commit -m "Deploy Build to GH Pages"
          git push -f -u origin ${{ env.BRANCH }}
          

      - name: Create PR for Build
        run: |
          gh pr create --repo ${{ env.REPO }} --base ${{ env.BASE }} --head ${{ env.BRANCH }} --title "Deploy Build by \#${{ github.actor }}" --body "Created automatically by merge to main"
      # - name: Create pull request
      #   uses: devops-infra/action-pull-request@master
      #   id: pr
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     source_branch: deploy-branch
      #     target_branch: gh-pages
      #     allow_no_diff: true
      #     label: deploy-pr
      #     title: "Deploy Site"
      #     reviewer: ajbarga