name: Build and Deploy Main Branch
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Build and Create PR
      uses: ajbarga/deploy-gh-pages@main
