name: Deploy
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Build and Deploy Main Branch
      uses: ajbarga/deploy-gh-pages@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        prTitle: "Deploy PR for commit"
        commit: "https://github.com/${{ github.repository }}/tree/${{ github.sha }}"
