name: Build and Deploy Main Branch
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write 
    steps:
    - uses: ajbarga/deploy-gh-pages@main

