name: Deploy
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.MY_PAT }}
    steps:
    - name: Build and Deploy Main Branch
      uses: ajbarga/deploy-gh-pages@main
      with:
        token: ${{ secrets.MY_PAT }}
