on:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          token: ${{secrets.GITHUB_TOKEN}}
          
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup Build repo
        run: |
          ls 
          ls -R
          cd ..
          ls
          mkdir deploy
          cd ./deploy
          ls
          git clone https://ajbarga:${{ secrets.MY_PAT }}@github.com/ajbarga/word-game.git
          cd ./word-game
          git checkout --force main
          npm i
          npm run build
          ls

      - name: Setup clone repo
        run: |
          cd ../..
          ls -R
          cd ./word-game
          ls -R
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b deploy-branch
          mv -f ../deploy/word-game/dist/*.* .
          git branch
          ls
          git add -f .
          git commit -m "Deploy Build"
          git push -f -u origin deploy-branch
          
      - name: Create pull request
        uses: devops-infra/action-pull-request@master
        id: pr
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: deploy-branch
          target_branch: gh-pages
          allow_no_diff: true
          label: deploy-pr
          title: "Deploy Site"
          reviewer: ajbarga