on:
  pull_request:
    types: 
     - opened 
     - reopened

jobs:
  approve-pr:
    name: Approve PR
    if: ${{ contains(github.event.head_commit.message, '#A') && github.actor == 'github-actions' }}
    runs-on: ubuntu-latest
    steps:
    - uses: ajbarga/deploy-gh-pages@v1
      with:
        token: ${{ secrets.MY_PAT }}
        merge: "${{ contains(github.event.head_commit.message, '#M') }}"
