on: 
  push:

jobs:
  copy-files:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.MY_PAT }}
      TEMPLATE: release-management
      DEST: test-repo
      ORG: ajbarga
      BRANCH: automatic-sync
      WORK_ITEM: 123abc
      COMMIT: "Docs: AutoSync Files from"
      PR_TITLE: "Patch: Complete first autosync"
      FILES: "'.github/workflows/release.yml', 'README.md'"
    steps:
    - name: Copy files
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@no-reply.github.com"
        
        git_base="https://${{ env.GITHUB_TOKEN }}@github.com/${{ env.ORG }}"

        # Clone sync-ing repository
        git clone ${git_base}/${{ env.DEST }}.git
        
        # Checkout branch
        cd ${{ env.DEST }}
        git checkout --force -b ${{ env.BRANCH }}
        
        cd ..
        
        # Clone src repo
        git clone ${git_base}/${{ env.TEMPLATE }}.git
        
    - name: Get ${{ env.TEMPLATE }} files
      run: |
        # Set list of files to copy
        files_to_copy=(${{ env.FILES }})
        
        # Enter cloned repository
        cd ${{ env.TEMPLATE }}

        # Copy specified files
        for file in "${files_to_copy[@]}"
        do
        cp -f $file ../${{ env.DEST }}/$file
        done

        # Navigate back to dest repo
        cd ../${{ env.DEST }}

        # Add copied files to repository
        for file in "${files_to_copy[@]}"
        do
        git add -f $file
        done

        git commit -m "${{ env.COMMIT }} ${{ env.TEMPLATE }}"
        
        # Push changes to remote repository
        git push -f -u origin ${{ env.BRANCH }}
    
    - name: Create / Edit PR for Build
      run: |
        gh pr create \
          --reviewer ajbarga \
          --base main \
          --head ${{ env.BRANCH }} \
          --title "${{ env.PR_TITLE }}" \
          --body "AutoSync PR created for @${{ github.actor }}." || \
        gh pr edit
          --reviewer ajbarga \
          --title "${{ env.PR_TITLE }}" \
          --body "AutoSync PR created for @${{ github.actor }}."
