on: 
  push:

jobs:
  copy-files:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.MY_PAT }}
      TEMPLATE: release-management
      DEST: test-repo
      ORG: ajbarga
      BRANCH: autosync
      WORK_ITEM: 123abc
    steps:
    - name: Copy files
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@no-reply.github.com"
        
        git_base="https://${{ env.TOKEN }}@github.com/${{ env.ORG }}"

        # Clone sync-ing repository
        git clone ${git_base}/${{ env.DEST }}.git
        
        # Checkout branch
        cd ${{ env.DEST }}
        git checkout --force -b ${{ env.BRANCH }}
        
        # Clone src repo
        git clone ${git_base}/${{ env.TEMPLATE }}.git
        
    - name: Get ${{ env.TEMPLATE }} files
      run: |
        # Set list of files to copy
        files_to_copy=('.github/workflows/release.yml')
        
        # Enter cloned repository
        cd ${{ env.TEMPLATE }}
        echo "template: "
        ls

        # Copy specified files
        for file in "${files_to_copy[@]}"
        do
        cp $file ../${{ env.DEST }}/$file
        done

        # Navigate back to dest repo
        cd ../${{ env.DEST }}
        echo "dest: "
        ls

        # Add copied files to repository
        for file in "${files_to_copy[@]}"
        do
        git add $file --force
        done

        git commit --force -m "Added AutoSync Files from ${{ env.TEMPLATE }} AB#${{ env.WORK_ITEM }}"
        # Push changes to remote repository
        git push --force origin ${{ env.BRANCH }}
