on: 
  push:

jobs:
  copy_files:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.MY_PAT }}
      TEMPLATE: release-management
      DEST: test-repo
      ORG: ajbarga
      BRANCH: autosync
    steps:
    - name: Copy files
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@no-reply.github.com"
        
        git_base="https://${{ env.TOKEN }}@github.com/${{ env.ORG }}"
        
        src_repo="${git_base}/${TEMPLATE}.git"
        dest_repo="${git_base}/${DEST}.git"

        # Set list of files to copy
        files_to_copy=('.github/workflows/release.yml')

        # Clone dest repository
        git clone $dest_repo
        
        # Checkout branch
        cd ${{ env.DEST }}
        git checkout --force -b ${{ env.BRANCH }}
        cd ..
        
        # Clone src repo
        git clone $src_repo

        # Enter cloned repository
        cd ${{ env.TEMPLATE }}

        # Copy specified files
        for file in "${files_to_copy[@]}"
        do
        cp $file ../${{ env.DEST }}/$file
        done

        # Navigate back to parent directory
        cd ..

        # Enter cloned repository
        cd ${{ env.DEST }}

        # Add copied files to repository
        for file in "${files_to_copy[@]}"
        do
        git add $file
        done

        # Commit changes
        git commit -m "Added specified files from source repository"

        # Push changes to remote repository
        git push --force origin main
